let express = require("express")
const { colorRoutes } = require("./colorRoute")
const { materialRoute } = require("./materialRoute")
const { countryRoutes } = require("./CountryRoute")
const { faqRoutes } = require("./faqRoute")
const { categoryRouts } = require("./categoryRoute")
const { whyChooseUsRoutes } = require("./whyChooseUsRoute")
const { sliderRoutes } = require("./sliderRoute")
const { subCategoryRoutes } = require("./subCategoryRoute")
const { subSubCategoryRoutes } = require("./subSubCategoryRoute")
const { ProductRoutes } = require("./productRoute")
const { adminAuthRoutes } = require("./adminAuthRoute")
const { userRoutes } = require("./userRoute")
let adminRoutes = express.Router()

//http://localhost:8000/admin/color
adminRoutes.use("/admin-auth", adminAuthRoutes)
adminRoutes.use("/color", colorRoutes)
adminRoutes.use("/material", materialRoute)
adminRoutes.use("/country", countryRoutes)
adminRoutes.use("/faq", faqRoutes)
adminRoutes.use("/category", categoryRouts)
adminRoutes.use("/why-choose-us", whyChooseUsRoutes)
adminRoutes.use("/slider", sliderRoutes)
adminRoutes.use("/sub-category", subCategoryRoutes)
adminRoutes.use("/sub-sub-category", subSubCategoryRoutes)
adminRoutes.use("/product", ProductRoutes)
adminRoutes.use("/user", userRoutes)

module.exports = { adminRoutes }